import yaml
import mistune
import re
from typing import Dict, Any, Tuple

class MarkdownParser:
    def __init__(self):
        self.markdown = mistune.create_markdown(plugins=['table', 'url', 'strikethrough'])

    def parse_file(self, file_path: str) -> Tuple[Dict[str, Any], str]:
        """
        Parses a markdown file with YAML frontmatter.
        Returns a tuple (metadata_dict, html_content).
        """
        with open(file_path, 'r', encoding='utf-8') as f:
            content = f.read()
        
        return self.parse_text(content)

    def parse_text(self, content: str) -> Tuple[Dict[str, Any], str]:
        """
        Parses markdown text with YAML frontmatter.
        """
        metadata, markdown_body = self._extract_frontmatter(content)
        html_content = self.markdown(markdown_body)
        return metadata, html_content

    def _extract_frontmatter(self, content: str) -> Tuple[Dict[str, Any], str]:
        """
        Extracts YAML frontmatter from the beginning of the file.
        """
        frontmatter_regex = re.compile(r'^---\s*\n(.*?)\n---\s*\n', re.DOTALL)
        match = frontmatter_regex.match(content)
        
        if match:
            yaml_content = match.group(1)
            try:
                metadata = yaml.safe_load(yaml_content) or {}
                # Return content after the frontmatter
                return metadata, content[match.end():]
            except yaml.YAMLError as e:
                print(f"Error parsing YAML frontmatter: {e}")
                return {}, content
        
        return {}, content

    def extract_line_items(self, html_content: str) -> list:
        """
        Helper to extract table data if needed, though usually handled by template.
        For now, we rely on the template rendering the HTML table generated by mistune.
        """
        pass


